// Names, order and icons observed in the reference picker on 2026-09-22.
// A listing identifies a platform; it does not imply an active streaming API.
export type Platform = { slug: string; name: string; icon: string };

export const platforms: readonly Platform[] = [
  {"slug":"nunomix","name":"NunoMix","icon":"/platform-icons/reference/NunoMix.webp"},
  {"slug":"dramabox","name":"DramaBox","icon":"/platform-icons/reference/dramabox.webp"},
  {"slug":"dramaverse","name":"DramaVerse","icon":"/platform-icons/reference/dramaverse.jpg"},
  {"slug":"dramawave","name":"DramaWave","icon":"/platform-icons/reference/dramawave.png"},
  {"slug":"flextv","name":"FlexTV","icon":"/platform-icons/reference/flextv.png"},
  {"slug":"flickreels","name":"FlickReels","icon":"/platform-icons/reference/flickreels.png"},
  {"slug":"freereels","name":"FreeReels","icon":"/platform-icons/reference/freereels.webp"},
  {"slug":"goodshort","name":"GoodShort","icon":"/platform-icons/reference/goodshort.png"},
  {"slug":"idrama","name":"iDrama","icon":"/platform-icons/reference/idrama.jpg"},
  {"slug":"melolo","name":"Melolo","icon":"/platform-icons/reference/melolo.webp"},
  {"slug":"netshort","name":"NetShort","icon":"/platform-icons/reference/netshort.webp"},
  {"slug":"shortmax","name":"ShortMax","icon":"/platform-icons/reference/shortmax.jpg"},
  {"slug":"stardust","name":"Stardust","icon":"/platform-icons/reference/stardust.png"},
  {"slug":"anime","name":"Anime","icon":"/platform-icons/reference/anime.png"},
  {"slug":"anyreel","name":"AnyReel","icon":"/platform-icons/reference/anyreels.png"},
  {"slug":"bonustv","name":"BonusTV","icon":"/platform-icons/reference/bonustv.png"},
  {"slug":"bstation","name":"Bstation","icon":"/platform-icons/reference/Bstation.png"},
  {"slug":"cubetv","name":"CubeTV","icon":"/platform-icons/reference/CubeTV.png"},
  {"slug":"donghua","name":"Donghua","icon":"/platform-icons/reference/donghua.png"},
  {"slug":"dotdrama","name":"DotDrama","icon":"/platform-icons/reference/dotdrama.png"},
  {"slug":"drakor","name":"Drakor","icon":"/platform-icons/reference/drakor.png"},
  {"slug":"drakorid","name":"DrakorID","icon":"/platform-icons/reference/drakorid.png"},
  {"slug":"dramabite","name":"Dramabite","icon":"/platform-icons/reference/dramabite.webp"},
  {"slug":"dramarush","name":"Dramarush","icon":"/platform-icons/reference/dramarush.jpg"},
  {"slug":"dynastyshorts","name":"Dynasty Shorts","icon":"/platform-icons/reference/dynastyshorts.webp"},
  {"slug":"freeshort","name":"FreeShort","icon":"/platform-icons/reference/freeshort.png"},
  {"slug":"fundrama","name":"FunDrama","icon":"/platform-icons/reference/fundrama.png"},
  {"slug":"happyshort","name":"HappyShort","icon":"/platform-icons/reference/happyshort.png"},
  {"slug":"huangdou","name":"HuangDou","icon":"/platform-icons/reference/huangdou.jpg"},
  {"slug":"kalostv","name":"KalosTV","icon":"/platform-icons/reference/kalostv.png"},
  {"slug":"lookseries","name":"LookSeries","icon":"/platform-icons/reference/lookseries.png"},
  {"slug":"lupacine","name":"Lupacine","icon":"/platform-icons/reference/lupacine.webp"},
  {"slug":"meloshort","name":"MeloShort","icon":"/platform-icons/reference/meloshort.webp"},
  {"slug":"microdrama","name":"MicroDrama","icon":"/platform-icons/reference/microdrama.jpg"},
  {"slug":"minishort","name":"Minishort","icon":"/platform-icons/reference/Minishort.png"},
  {"slug":"moboreels","name":"MoboReels","icon":"/platform-icons/reference/moboreels.png"},
  {"slug":"moreshort","name":"MoreShort","icon":"/platform-icons/reference/moreshort.png"},
  {"slug":"mymuse","name":"My Muse","icon":"/platform-icons/reference/mymuse.webp"},
  {"slug":"mydrama","name":"MyDrama","icon":"/platform-icons/reference/mydrama.webp"},
  {"slug":"pinedrama","name":"PineDrama","icon":"/platform-icons/reference/pinedrama.png"},
  {"slug":"playlet","name":"Playlet","icon":"/platform-icons/reference/playlet.jpg"},
  {"slug":"radreel","name":"RadReel","icon":"/platform-icons/reference/radreel.webp"},
  {"slug":"reelala","name":"Reelala","icon":"/platform-icons/reference/Reelala.png"},
  {"slug":"reellife","name":"ReelLife","icon":"/platform-icons/reference/reellife.png"},
  {"slug":"reelshort","name":"ReelShort","icon":"/platform-icons/reference/reelshort.webp"},
  {"slug":"shortswave","name":"ShortsWave","icon":"/platform-icons/reference/shortswave.webp"},
  {"slug":"sixthshort","name":"SixthShort","icon":"/platform-icons/reference/sixthshort.png"},
  {"slug":"snackshort","name":"SnackShort","icon":"/platform-icons/reference/snackshort.png"},
  {"slug":"sodareels","name":"SodaReels","icon":"/platform-icons/reference/sodareels.png"},
  {"slug":"soreel","name":"SoReel","icon":"/platform-icons/reference/soreel.webp"},
  {"slug":"starreel","name":"StarReel","icon":"/platform-icons/reference/starreel.png"},
  {"slug":"storyreel","name":"StoryReel","icon":"/platform-icons/reference/storyreel.webp"},
  {"slug":"velolo","name":"Velolo","icon":"/platform-icons/reference/velolo.png"},
  {"slug":"vibeshort","name":"VibeShort","icon":"/platform-icons/reference/vibeshort.webp"},
  {"slug":"vigloo","name":"Vigloo","icon":"/platform-icons/reference/vigloo.png"},
  {"slug":"wetv","name":"WeTV","icon":"/platform-icons/reference/wetv.png"},
];

