-- Match the 56-platform selector without replacing existing UUIDs or series.
alter table public.platforms add column if not exists icon_url text;

insert into public.platforms (slug, name, position, icon_url) values
  ('nunomix', 'NunoMix', 1, '/platform-icons/reference/NunoMix.webp'),
  ('dramabox', 'DramaBox', 2, '/platform-icons/reference/dramabox.webp'),
  ('dramaverse', 'DramaVerse', 3, '/platform-icons/reference/dramaverse.jpg'),
  ('dramawave', 'DramaWave', 4, '/platform-icons/reference/dramawave.png'),
  ('flextv', 'FlexTV', 5, '/platform-icons/reference/flextv.png'),
  ('flickreels', 'FlickReels', 6, '/platform-icons/reference/flickreels.png'),
  ('freereels', 'FreeReels', 7, '/platform-icons/reference/freereels.webp'),
  ('goodshort', 'GoodShort', 8, '/platform-icons/reference/goodshort.png'),
  ('idrama', 'iDrama', 9, '/platform-icons/reference/idrama.jpg'),
  ('melolo', 'Melolo', 10, '/platform-icons/reference/melolo.webp'),
  ('netshort', 'NetShort', 11, '/platform-icons/reference/netshort.webp'),
  ('shortmax', 'ShortMax', 12, '/platform-icons/reference/shortmax.jpg'),
  ('stardust', 'Stardust', 13, '/platform-icons/reference/stardust.png'),
  ('anime', 'Anime', 14, '/platform-icons/reference/anime.png'),
  ('anyreel', 'AnyReel', 15, '/platform-icons/reference/anyreels.png'),
  ('bonustv', 'BonusTV', 16, '/platform-icons/reference/bonustv.png'),
  ('bstation', 'Bstation', 17, '/platform-icons/reference/Bstation.png'),
  ('cubetv', 'CubeTV', 18, '/platform-icons/reference/CubeTV.png'),
  ('donghua', 'Donghua', 19, '/platform-icons/reference/donghua.png'),
  ('dotdrama', 'DotDrama', 20, '/platform-icons/reference/dotdrama.png'),
  ('drakor', 'Drakor', 21, '/platform-icons/reference/drakor.png'),
  ('drakorid', 'DrakorID', 22, '/platform-icons/reference/drakorid.png'),
  ('dramabite', 'Dramabite', 23, '/platform-icons/reference/dramabite.webp'),
  ('dramarush', 'Dramarush', 24, '/platform-icons/reference/dramarush.jpg'),
  ('dynastyshorts', 'Dynasty Shorts', 25, '/platform-icons/reference/dynastyshorts.webp'),
  ('freeshort', 'FreeShort', 26, '/platform-icons/reference/freeshort.png'),
  ('fundrama', 'FunDrama', 27, '/platform-icons/reference/fundrama.png'),
  ('happyshort', 'HappyShort', 28, '/platform-icons/reference/happyshort.png'),
  ('huangdou', 'HuangDou', 29, '/platform-icons/reference/huangdou.jpg'),
  ('kalostv', 'KalosTV', 30, '/platform-icons/reference/kalostv.png'),
  ('lookseries', 'LookSeries', 31, '/platform-icons/reference/lookseries.png'),
  ('lupacine', 'Lupacine', 32, '/platform-icons/reference/lupacine.webp'),
  ('meloshort', 'MeloShort', 33, '/platform-icons/reference/meloshort.webp'),
  ('microdrama', 'MicroDrama', 34, '/platform-icons/reference/microdrama.jpg'),
  ('minishort', 'Minishort', 35, '/platform-icons/reference/Minishort.png'),
  ('moboreels', 'MoboReels', 36, '/platform-icons/reference/moboreels.png'),
  ('moreshort', 'MoreShort', 37, '/platform-icons/reference/moreshort.png'),
  ('mymuse', 'My Muse', 38, '/platform-icons/reference/mymuse.webp'),
  ('mydrama', 'MyDrama', 39, '/platform-icons/reference/mydrama.webp'),
  ('pinedrama', 'PineDrama', 40, '/platform-icons/reference/pinedrama.png'),
  ('playlet', 'Playlet', 41, '/platform-icons/reference/playlet.jpg'),
  ('radreel', 'RadReel', 42, '/platform-icons/reference/radreel.webp'),
  ('reelala', 'Reelala', 43, '/platform-icons/reference/Reelala.png'),
  ('reellife', 'ReelLife', 44, '/platform-icons/reference/reellife.png'),
  ('reelshort', 'ReelShort', 45, '/platform-icons/reference/reelshort.webp'),
  ('shortswave', 'ShortsWave', 46, '/platform-icons/reference/shortswave.webp'),
  ('sixthshort', 'SixthShort', 47, '/platform-icons/reference/sixthshort.png'),
  ('snackshort', 'SnackShort', 48, '/platform-icons/reference/snackshort.png'),
  ('sodareels', 'SodaReels', 49, '/platform-icons/reference/sodareels.png'),
  ('soreel', 'SoReel', 50, '/platform-icons/reference/soreel.webp'),
  ('starreel', 'StarReel', 51, '/platform-icons/reference/starreel.png'),
  ('storyreel', 'StoryReel', 52, '/platform-icons/reference/storyreel.webp'),
  ('velolo', 'Velolo', 53, '/platform-icons/reference/velolo.png'),
  ('vibeshort', 'VibeShort', 54, '/platform-icons/reference/vibeshort.webp'),
  ('vigloo', 'Vigloo', 55, '/platform-icons/reference/vigloo.png'),
  ('wetv', 'WeTV', 56, '/platform-icons/reference/wetv.png')
on conflict (slug) do update set
  name = excluded.name,
  position = excluded.position,
  icon_url = excluded.icon_url;

